stages:
  - build
  - deploy
  
services:
  - docker:dind

variables:
  DOCKER_HOST: "tcp://docker:2375"
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  DOCKERHUB_USERNAME: balajisukumaran96

build_ui:
  stage: build
  script:
    - cd ui/walletwatch-dashboard
    - echo $PATH
    - docker build -t wallet-watch:ui .
    - docker tag wallet-watch:ui $DOCKERHUB_USERNAME/wallet-watch:ui
    - echo "$DOCKERHUB_PASSWORD" | docker login -u $DOCKERHUB_USERNAME --password-stdin
    - docker push $DOCKERHUB_USERNAME/wallet-watch:ui
    
build_server:
  stage: build
  script:
    - cd server/com.walletwatch.api
    - docker build --build-arg AWS_ACCESS_KEY_ID = $AWS_ACCESS_KEY_ID --build-arg AWS_SECRET_ACCESS_KEY = $AWS_SECRET_ACCESS_KEY -t wallet-watch:server .
    #- docker build -t wallet-watch:server .
    - docker tag wallet-watch:server $DOCKERHUB_USERNAME/wallet-watch:server
    - echo "$DOCKERHUB_PASSWORD" | docker login -u $DOCKERHUB_USERNAME --password-stdin
    - docker push $DOCKERHUB_USERNAME/wallet-watch:server

deploy:
  stage: deploy
  script:
    - echo "Running application..."
