stages:
  - build
  - deploy

variables:
  DOCKERHUB_USERNAME: balajisukumaran96

build_ui:
  stage: build
  script:
    - cd ui/walletwatch-dashboard
    - echo $PATH
    - DOCKER_BUILDKIT=1 sudo docker build -t wallet-watch:ui .
    - sudo docker tag wallet-watch:ui $DOCKERHUB_USERNAME/wallet-watch:ui
    - echo "$DOCKERHUB_PASSWORD" | sudo docker login -u $DOCKERHUB_USERNAME --password-stdin
    - sudo docker push $DOCKERHUB_USERNAME/wallet-watch:ui

build_server:
  stage: build
  script:
    - cd server/com.walletwatch.api
    - sudo docker build -t wallet-watch:server .
    - sudo docker tag wallet-watch:server $DOCKERHUB_USERNAME/wallet-watch:server
    - echo "$DOCKERHUB_PASSWORD" | sudo docker login -u $DOCKERHUB_USERNAME --password-stdin
    - sudo docker push $DOCKERHUB_USERNAME/wallet-watch:server

deploy:
  stage: deploy
  script:
    - docker-compose -f docker-compose.yml up -d
