AWSTemplateFormatVersion: "2010-09-09"
Description: Wallet Watch Secrets Manager secret with placeholders for key/value pairs.

Resources:
  WalletWatchSecret:
    Type: "AWS::SecretsManager::Secret"
    Properties:
      Name: WalletWatchSecret
      Description: "Secret store for wallet watch application"
      SecretString: '
        {
          "rds_url": "url",
          "rds_username": "MasterUsername",
          "rds_password": "secret-password",
          "spring_mail_protocol": "smtp",
          "spring_mail_host": "smtp.gmail.com",
          "spring_mail_port": 465,
          "spring_mail_username": "rentxmailservice@gmail.com",
          "spring_mail_password": "kjxvsktjrrddotof",
          "spring_mail_properties_mail_smtp_auth": true,
          "spring_mail_properties_mail_smtp_starttls_enable": true,
          "mail_smtp_starttls_enable": false,
          "spring_mail_properties_mail_smtp_ssl_enable": true,
          "spring_mail_properties_mail_smtp_starttls_required": true,
          "allowed_origin": "http://localhost:8080",
          "system_email": "rentxmailservice@gmail.com"
        }
      '
      Tags:
        - Key: AppName
          Value: WalletWatch

Outputs:
  WalletWatchSecretArn:
    Description: "ARN of the created secret"
    Value: !Ref WalletWatchSecret
    Export:
      Name: !Sub "${AWS::StackName}-SecretArn"

  WalletWatchSecretName:
    Description: "Name of the created secret"
    Value: WalletWatchSecret
    Export:
      Name: !Sub "${AWS::StackName}-SecretName"



